#!/bin/bash

# To add the toolkit add the follwing line in your .bashrc file
# export TOOLKIT_DIR="" && source $TOOLKIT_DIR/main


# ===========================================
# ALIAS list
# ===========================================
# System
alias ll="ls -lhaF"
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias install="sudo apt install -y"
alias update="sudo apt update"
alias upgrade="sudo apt update && sudo apt --only-upgrade install"
alias delete="sudo apt purge --auto-remove"

#Webfleet
alias webfleet="cd /mnt/c/Users/pelegrin/Documents/WebfleetProjects"

# Kubernetes
alias k='kubectl'
alias ksetns='f(){ kubectl config set-context --current --namespace=$1; }; f'

alias kpods='kubectl get pods'
alias kservices='kubectl get services'
alias klogs='f(){ kubectl logs $1; }; f'
alias kexec='f(){ kubectl exec --stdin --tty $1 -- /bin/bash; }; f'
alias kshell="kubectl run shell --rm -i --tty --image ubuntu -- bash"

# Docker
alias dk="docker"
alias dk-get-tags='f(){ curl -L -s "https://$1/v2/$2/tags/list"; }; f'
alias dk-start-all='docker start $(docker ps -aq)'
alias dk-stop-all='docker stop $(docker ps -aq)'
alias dk-clean='docker system prune -a'
alias dk-purge='docker stop $(docker ps -aq) && docker system prune --volumes -a '

# Ansible
alias ansible="source $TOOLKIT_DIR/.venv/bin/activate && ansible"

# ===========================================
# BIN directory
# ===========================================
chmod -R +x $TOOLKIT_DIR/bin/
export PATH="$PATH:$TOOLKIT_DIR/bin"


# ===========================================
# SCRIPTS directory
# ===========================================
chmod -R +x $TOOLKIT_DIR/scripts/

# INITIALIZATION ============================
$TOOLKIT_DIR/scripts/init.sh
