#!/bin/bash

# To add the toolkit add the follwing line in your .bashrc file
# export TOOLKIT_DIR="" && source $TOOLKIT_DIR/main


# ===========================================
# ALIAS list
# ===========================================
# System
alias ll="ls -lhaF"
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias install="sudo apt install -y"
alias update="sudo apt update"
alias upgrade="sudo apt update && sudo apt --only-upgrade install"
alias delete="sudo apt purge --auto-remove"

#Webfleet
alias webfleet="cd /mnt/c/Users/pelegrin/Documents/WebfleetProjects"

# Kubernetes
alias kk="kubectl"
alias kk-setns="f(){ kubectl config set-context --current --namespace=@1; }; f"
alias kk-exec='f(){ kubectl exec --stdin --tty @1 -- /bin/bash; }; f'

# Docker
alias dk="docker"
alias dk-start-all='docker start $(docker ps -aq)'
alias dk-stop-all='docker stop $(docker ps -aq)'
alias dk-clean='docker system prune -a'
alias dk-purge='docker stop $(docker ps -aq) && docker system prune --volumes -a '

# Ansible
alias ansible="source $TOOLKIT_DIR/.venv/bin/activate && ansible"

# ===========================================
# BIN directory
# ===========================================
chmod -R +x $TOOLKIT_DIR/bin/
export PATH="$PATH:$TOOLKIT_DIR/bin"


# ===========================================
# SCRIPTS directory
# ===========================================
chmod -R +x $TOOLKIT_DIR/scripts/

# INITIALIZATION ============================
$TOOLKIT_DIR/scripts/init.sh
